---
title: "P3 Darkkhaki"
author: "Zhang XiangHui, Lin Weichen, Priscilla Thung, Tang Guan You, Arshad Bin Mazlan, Wong Jing Yong Shawn"
date: "2024-06-29"
format: html
editor: visual
---

# Introduction

## Load necessary packages

```{r}
#| label: setup
#| message: false
#| warning: false

library(dplyr)
library(ggplot2)
library(usmap)
library(scales)
library(tidyverse)
library(sf)
library(ggtext)
library(stringr)
```

## Data cleaning and transformation

```{r}
#| message: false

# Load the restaurants 2020 data
restaurants_2020 <- read_csv("restaurants_2020.csv") |>
  drop_na(addressRegion)

# Load the restaurants 2023 data
restaurants_2023 <- read_csv("restaurants_2023.csv") |>
  drop_na(full_address)

# Extract the state abbreviation using a regular expression and clean it up
restaurants_2023 <- restaurants_2023 %>%
  mutate(state = str_extract(full_address, ",\\s*([A-Z]{2})\\s*,") %>%
           str_replace_all("^,\\s*|\\s*,$", ""))

# Select the state and Year Partnered columns
restaurants_2023 <- restaurants_2023 %>%
  select(id, state, name)

# Add a year partnered column to the 2023 dataset
restaurants_2023 <- restaurants_2023 %>%
  mutate(`Year Partnered` = NaN)
```

## Group the restaurants by state

```{r}
# Rename 2020 data addressRegion not state
restaurants_2020 %>%
  rename(
    state = addressRegion
  )

# Add a Year Partnered column to the 2020 dataset
restaurants_2020 <- restaurants_2020 %>%
  mutate(Year_Partnered = 2020)

# Add a Year Partnered column to the 2023 dataset
filtered_restaurants <- restaurants_2023 %>%
  mutate(`Year Partnered` = ifelse(name %in% restaurants_2020$name, 2020, 2023))
```

## Merge the two datasets and calculate the percentage difference

```{r}
# Group the data by state and year
grouped_restaurants <- filtered_restaurants |>
  group_by(state, `Year Partnered`) |>
  summarise(count = n())

# Calculate the percentage increase after each year
# Take NaN as 0 to show no increase in restaurants
filtered_data <- grouped_restaurants |>
  group_by(state) |>
  mutate(percentage_diff = if_else(is.na(lag(count)), 0,
                                   (count - lag(count)) / lag(count) * 100))

filtered_data
```

## Prepare data for plotting

```{r}
# Get state centroids for labeling
state_coords <- usmap::us_map(regions = "states")

# Convert to an sf object
state_coords_sf <- st_as_sf(state_coords, coords = c("long", "lat"), crs = 4326
                            , agr = "constant")

# Calculate centroids for each state
state_centroids <- state_coords_sf %>%
  st_centroid() %>%
  st_coordinates() %>%
  as_tibble() %>%
  bind_cols(state_coords_sf)

# Prepare data for centroid labels
state_centroids <- state_centroids %>%
  rename(lon = X, lat = Y) %>%
  select(abbr, lon, lat)

# Print state centroids before adjustments
print(state_centroids %>% filter(abbr %in% c("FL", "HI")))

# Adjust the coordinates for FL and HI
state_centroids <- state_centroids %>%
  mutate(
    lon = if_else(abbr == "FL", lon + 150000, lon),
    lat = if_else(abbr == "FL", lat - 100000, lat),
    lon = if_else(abbr == "HI", lon + 100000, lon),
    lat = if_else(abbr == "HI", lat - 75000, lat)
  )

# Print state centroids after adjustments
print(state_centroids %>% filter(abbr %in% c("FL", "HI")))

# Find missing states (states with no data)
all_states <- unique(state_centroids$abbr)
plotted_states <- unique(filtered_data$state)
missing_states <- setdiff(all_states, plotted_states)

# Define a list of states with smaller areas 
# (For a smaller size of the label text)
small_area_states <- c("CT", "DE", "DC", "HI", "MD",
                       "MA", "NH", "NJ", "RI")

# Prepare state_labels for plotting
state_labels <- state_centroids %>%
  left_join(filtered_data, by = c("abbr" = "state")) %>%
  mutate(
    label_color = ifelse(is.na(percentage_diff) | percentage_diff <= 200
                         , "black", "white"),
    label_size = ifelse(abbr %in% small_area_states, 1.5, 3)
  )

# Prepare centroid_labels for states with no data
centroid_labels <- state_centroids %>%
  mutate(
    label_text = ifelse(abbr %in% missing_states, abbr, ""),
    label_size = ifelse(abbr %in% small_area_states, 1.5, 3)
  )

```

## Plot the US map with percentage increase

```{r}
# Define the breaks for the color scale
breaks <- c(-100, 0, 50, 100, 200, 300)

# Plotting the US map with the percentage increase
plot_usmap(data = filtered_data, values = "percentage_diff", color = "white") +
  theme(legend.position = "right") +
  scale_fill_fermenter(palette = "YlOrBr", breaks = breaks,
                       name = "Percentage Increase",
                       labels = percent_format(scale = 1),
                       direction = 1) +
  labs(title = "Increase in virtual restaurants by State",
       subtitle = "between 2020 and 2023",
       caption = "**Source**: Kaggle Dataset of Uber Eats USA Restaurants
       and Github \"gsunit\" Uber Eats Scraping") +
  theme(
    plot.caption = element_markdown(),
    legend.title = element_text(size = 10, hjust = 0.5),
    legend.text = element_text(size = 8),
    plot.title = element_text(hjust = 0.5, size = 16),
    plot.subtitle = element_text(hjust = 0.5, size = 12),
    legend.position = "top",  # Position legend at the top
    legend.box = "vertical",  # Arrange legends vertically
    legend.key.width = unit(1, "cm"),  # Set legend key width
    legend.frame = element_rect(), # Add a frame around the legend
    legend.margin = margin(t = 1, unit = "pt"),
    legend.title.position = "top",
  )  +
  geom_text(data = state_labels, aes(
    x = lon, y = lat,
    label = abbr,
    color = label_color,
    size = label_size
  )) +
  geom_text(data = centroid_labels, aes(
    x = lon, y = lat,
    label = label_text,
    size = label_size,
  ), color = "black") +
  scale_color_identity() +
  scale_size_identity() +
  theme(
    # Change the panel background color
    panel.background = element_rect(fill = "aliceblue", color = NA),
    # Change the plot background color
    plot.background = element_rect(fill = "white", color = NA),
  )
```
